name: Actionlint

on:
  push:
    branches: [main]
    paths: ['.github/workflows/**', '.github/actionlint.yaml']
  pull_request:
    paths: ['.github/workflows/**', '.github/actionlint.yaml']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Actions Toolbox
        uses: wallentx/gh-actions/composite/actions-toolbox@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          checkout: false

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
